### ISSUE TITLE
You're using markdown markup

### ISSUE THREAD

**Issue by KingMob** [NinjasCL/adr-asciidoc#1]
Kind of ironic for an AsciiDoc project

**Comment by clsource** [comment]
titles using `#` are valid asciidoc, so why not? xd.
if they were markdown it won't compile using asciidoctor.

**Comment by KingMob** [comment]
@clsource 

> if they were markdown it won't compile using asciidoctor.

That's not true. AsciiDoc accepts Markdown headers for compatibility, but they aren't the [standard](https://docs.asciidoctor.org/asciidoc/latest/sections/titles-and-levels/), and may confuse people new to AsciiDoc, reading the documentation, and wondering why hash marks aren't used everywhere.

If the purpose of this project isn't to promote AsciiDoc, then what's it for?

**Comment by clsource** [comment]
from the docs:
> In addition to the equals sign marker used for defining section titles, Asciidoctor recognizes the hash symbol (#) from Markdown. That means the outline of a Markdown document will be converted just fine as an AsciiDoc document. 

In my experience most people come from markdown syntax. So I prefer to have *familiarity*. Using a similar sintax gives you one less thing to learn.

**Comment by clsource** [comment]
from the docs:
> In addition to the equals sign marker used for defining section titles, Asciidoctor recognizes the hash symbol (#) from Markdown. That means the outline of a Markdown document will be converted just fine as an AsciiDoc document. 

In my experience most people come from markdown syntax. So I prefer to have *familiarity*. Using a similar sintax gives you one less thing to learn.

**Comment by KingMob** [comment]
That's a valid perspective, but I suspect people looking for familiarity will avoid an AsciiDoc-based template entirely.

I don't know about your other users, but I tried this because I wanted to learn and use more AsciiDoc. I chose AsciiDoc because I wanted to get away from some of the irritants of Markdown.
